name: clean_architecture_example
description: Weather app.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.3
  get: ^4.6.1
  get_it: ^7.2.0
  glassmorphism: ^3.0.0
  google_fonts: ^2.3.2
  http: ^0.13.4
  import_sorter: ^4.6.0
  injectable: ^1.5.3

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  injectable_generator: ^1.5.3
  mockito: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
